# The URL the site will be built for
base_url = "https://hashbangcore.github.com"
default_language = "es"
generate_feeds = true
feed_filenames = ["atom.xml"]
theme = "default"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[languages.es]
build_search_index = true
generate_feeds = true

[languages.en]
build_search_index = true
generate_feeds = true

[markdown]

[markdown.highlighting]
style = "class"
light_theme = "github-dark"
dark_theme = "github-light"

[extra]
# Put all your custom variables here
